# Purpose

Is it really possible to quickly filter the neurons of a deep neural network?

In [1]:
import torch

In [7]:
# generates random ints, up to the bound, of size "bound"
torch.randperm(5)

tensor([1, 0, 4, 2, 3])

In [21]:
def check_active(x, y):
    '''For now: compare x and y, returning x == y, just so I know what that really does
    
    Args:
        x: tensor of activations
        y: scalar tensor (broadcasted), or tensor of x.shape, to compare against x
    
    Future plans:
        1. I would like to "filter" the activations `x` based on some relationship with `y`
    '''
    return (x == y)

In [27]:
check_active(torch.randperm(5), torch.randperm(5))

tensor([0, 1, 0, 0, 0], dtype=torch.uint8)

This is analogous to `is_alive` or some such other neuroscience-based vocabulary describing the state of neuron

---

In [37]:
def make_tensor_with_gradients():
    t = torch.tensor(5., requires_grad=True)
    
    z = t * 2
    print(t, z)
    
    print('t.grad', t.grad)
    print('z.grad', z.grad)
    
    print(z.backward())
    print('t.grad', t.grad)
    print('z.grad', z.grad)
    

make_tensor_with_gradients()

tensor(5., requires_grad=True) tensor(10., grad_fn=<MulBackward0>)
t.grad None
z.grad None
None
t.grad tensor(2.)
z.grad None


In [41]:
?torch.cat

In [60]:
torch.cat((torch.empty(3), torch.empty(3)))

tensor([ 0.0000e+00,  3.6893e+19, -1.1811e-36,  0.0000e+00,  3.6893e+19,
        -1.1810e-36])

In [86]:
def widen(layer, factor=1.3):
    print('Widening layer of size', len(layer))
    print('\tnew size =', round(len(layer) * factor + .5))
    
    new_size = round(len(layer) * factor)
    size_diff = new_size - len(layer)
    
    print('\tchange in size=', size_diff)
    if size_diff % 2 == 1: size_diff = size_diff + 1 # evens are easier

    concat_half_size = size_diff // 2
    print('\tempty tensors will have size', concat_half_size)

    # pull from the normal distribution, try to blend in with your new layers
    _layer_std = torch.std(layer).unsqueeze(-1)
    
    # then we return the concatenation
    return torch.cat(
              [torch.normal(_layer_std),
              layer,
              torch.normal(_layer_std)], dim=-1)

widen(torch.randn(5))

Widening layer of size 5
	new size = 7
	change in size= 1
	empty tensors will have size 1


tensor([ 0.2043,  0.2724,  0.1472,  0.4794, -0.3290, -0.3808, -0.2636])