In [1]:
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [8]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -2.0000e+00,  0.0000e+00],
        [-2.0000e+00,  7.0065e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -2.0000e+00,  5.2392e-27]])


Construct a randomly initialized matrix:



In [12]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7277, 0.1231, 0.6692],
        [0.4479, 0.6775, 0.5339],
        [0.2785, 0.5352, 0.7729],
        [0.3870, 0.1001, 0.2372],
        [0.9663, 0.5611, 0.7871]])


**Me**: what other (non-uniform) randoms are there?

In [13]:
dir(torch.random)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_fork_rng_warned_already',
 'contextlib',
 'default_generator',
 'fork_rng',
 'get_rng_state',
 'initial_seed',
 'manual_seed',
 'set_rng_state',
 'torch',
 'warnings']

In [16]:
[x for x in dir(torch) if x.startswith('rand')]

['rand',
 'rand_like',
 'randint',
 'randint_like',
 'randn',
 'randn_like',
 'random',
 'randperm']

In [21]:
torch.randn(5, 3) # <- that's the 'n' for 'normal' (Guassian) distribution

tensor([[-0.8153, -0.1240,  1.3091],
        [-0.0613,  2.2162,  0.1099],
        [ 1.0880, -0.6627,  1.9750],
        [-0.9987,  0.5986,  0.9875],
        [ 0.3189, -1.2340, -1.3810]])

In [35]:
torch.randperm(6)

tensor([3, 0, 4, 5, 1, 2])

This is really interesting. It's a two-in-one functions:
1. Generates `n` random numbers
2. They are between 0 and `n`

In [48]:
torch.randint(6, (2,))

tensor([0, 3])

This `randint` is much more configurable:
> Give randoms in `[0, 6)`. I want them in the shape (size) `(2,)`
* In other words give me 2 random integers `[0, 6)`

In [63]:
torch.rand(2) # this is the equivalent of the above

tensor([0.3659, 0.3498])

---

Construct a matrix filled zeros and of dtype long:



In [67]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [68]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [72]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1195,  0.2739, -0.4100],
        [-2.0329,  0.0904,  0.4086],
        [-0.2687, -1.7348,  1.3089],
        [ 0.8688, -0.3147, -0.3456],
        [ 0.9244,  0.3889, -0.1039]])


Get its size:



In [73]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [74]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.7109,  0.5609,  0.0139],
        [-1.0550,  0.6202,  0.6099],
        [ 0.1905, -0.9904,  2.1101],
        [ 0.9852,  0.3348, -0.0415],
        [ 1.1659,  0.6517,  0.8088]])


Addition: syntax 2



In [75]:
print(torch.add(x, y))

tensor([[ 0.7109,  0.5609,  0.0139],
        [-1.0550,  0.6202,  0.6099],
        [ 0.1905, -0.9904,  2.1101],
        [ 0.9852,  0.3348, -0.0415],
        [ 1.1659,  0.6517,  0.8088]])


Addition: providing an output tensor as argument



In [76]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.7109,  0.5609,  0.0139],
        [-1.0550,  0.6202,  0.6099],
        [ 0.1905, -0.9904,  2.1101],
        [ 0.9852,  0.3348, -0.0415],
        [ 1.1659,  0.6517,  0.8088]])


Addition: in-place



In [77]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.7109,  0.5609,  0.0139],
        [-1.0550,  0.6202,  0.6099],
        [ 0.1905, -0.9904,  2.1101],
        [ 0.9852,  0.3348, -0.0415],
        [ 1.1659,  0.6517,  0.8088]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [79]:
print(x[:, 1])

tensor([ 0.2739,  0.0904, -1.7348, -0.3147,  0.3889])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [82]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [83]:
y, z

(tensor([ 0.6095,  0.2553, -1.6599,  0.8783, -0.0866, -0.8526,  0.7792,  0.5944,
          1.4772, -0.0895,  1.6246, -1.2565, -1.0698, -0.4060, -0.1048, -1.2720]),
 tensor([[ 0.6095,  0.2553, -1.6599,  0.8783, -0.0866, -0.8526,  0.7792,  0.5944],
         [ 1.4772, -0.0895,  1.6246, -1.2565, -1.0698, -0.4060, -0.1048, -1.2720]]))

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [84]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.3806])
-1.3806071281433105


**Me**: what happens when you call `.item()` when you have more than one element?

In [85]:
q = torch.randn(2)
print(q)
# print(q.item()) # <- it throws a ValueError :P

tensor([-0.1274, -0.6768])


ValueError: only one element tensors can be converted to Python scalars

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [86]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [87]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [88]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


**Me**: Prove that the `numpy.array` is a back-pointer, or reference, to the data made by `torch`

Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [89]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**Me**: Here we see that `torch` also makes the back-pointer

All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [90]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!